# Generated by Django 5.0 on 2023-12-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='script_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
