# Generated by Django 5.0 on 2023-12-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productprice_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RenameField(
            model_name='productprice',
            old_name='date',
            new_name='timestamp',
        ),
    ]
